// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrGY-gp5f9xM5qmvXcoqG6Kf8idPtg50',
    appId: '1:649199618610:web:991c6949b1112cceb30a2b',
    messagingSenderId: '649199618610',
    projectId: 'ezbuy-103d1',
    authDomain: 'ezbuy-103d1.firebaseapp.com',
    storageBucket: 'ezbuy-103d1.firebasestorage.app',
    measurementId: 'G-W3CQZFV4M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgA39dz-ZgErl8ZIhBhHLLdPHuG7jIvvg',
    appId: '1:649199618610:android:18d80081d29e01c8b30a2b',
    messagingSenderId: '649199618610',
    projectId: 'ezbuy-103d1',
    storageBucket: 'ezbuy-103d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc8tfI8nh_q22F7X_jeJ7JA5uK7bjEoso',
    appId: '1:649199618610:ios:2ce02f6a1d32855fb30a2b',
    messagingSenderId: '649199618610',
    projectId: 'ezbuy-103d1',
    storageBucket: 'ezbuy-103d1.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc8tfI8nh_q22F7X_jeJ7JA5uK7bjEoso',
    appId: '1:649199618610:ios:2ce02f6a1d32855fb30a2b',
    messagingSenderId: '649199618610',
    projectId: 'ezbuy-103d1',
    storageBucket: 'ezbuy-103d1.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxrGY-gp5f9xM5qmvXcoqG6Kf8idPtg50',
    appId: '1:649199618610:web:8c92830c4b5bcda5b30a2b',
    messagingSenderId: '649199618610',
    projectId: 'ezbuy-103d1',
    authDomain: 'ezbuy-103d1.firebaseapp.com',
    storageBucket: 'ezbuy-103d1.firebasestorage.app',
    measurementId: 'G-1TBMPW2GGF',
  );
}
